# Copyright 2015.
#   Michael A. DeJesus, Chaitra Ambadipudi, and  Thomas R. Ioerger.
#
#
#    This file is part of TRANSIT.
#
#    TRANSIT is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License.
#
#
#    TRANSIT is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with TRANSIT.  If not, see <http://www.gnu.org/licenses/>.


#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

TRANSIT = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAOgAAABCCAMAAABq8GrCAAAAA3NCSVQICAjb4U/gAAADAFBM"
    "VEUAAAAAADMAAGYAAJkAAMwAAP8AMwAAMzMAM2YAM5kAM8wAM/8AZgAAZjMAZmYAZpkAZswA"
    "Zv8AmQAAmTMAmWYAmZkAmcwAmf8AzAAAzDMAzGYAzJkAzMwAzP8A/wAA/zMA/2YA/5kA/8wA"
    "//8zAAAzADMzAGYzAJkzAMwzAP8zMwAzMzMzM2YzM5kzM8wzM/8zZgAzZjMzZmYzZpkzZswz"
    "Zv8zmQAzmTMzmWYzmZkzmcwzmf8zzAAzzDMzzGYzzJkzzMwzzP8z/wAz/zMz/2Yz/5kz/8wz"
    "//9mAABmADNmAGZmAJlmAMxmAP9mMwBmMzNmM2ZmM5lmM8xmM/9mZgBmZjNmZmZmZplmZsxm"
    "Zv9mmQBmmTNmmWZmmZlmmcxmmf9mzABmzDNmzGZmzJlmzMxmzP9m/wBm/zNm/2Zm/5lm/8xm"
    "//+ZAACZADOZAGaZAJmZAMyZAP+ZMwCZMzOZM2aZM5mZM8yZM/+ZZgCZZjOZZmaZZpmZZsyZ"
    "Zv+ZmQCZmTOZmWaZmZmZmcyZmf+ZzACZzDOZzGaZzJmZzMyZzP+Z/wCZ/zOZ/2aZ/5mZ/8yZ"
    "///MAADMADPMAGbMAJnMAMzMAP/MMwDMMzPMM2bMM5nMM8zMM//MZgDMZjPMZmbMZpnMZszM"
    "Zv/MmQDMmTPMmWbMmZnMmczMmf/MzADMzDPMzGbMzJnMzMzMzP/M/wDM/zPM/2bM/5nM/8zM"
    "////AAD/ADP/AGb/AJn/AMz/AP//MwD/MzP/M2b/M5n/M8z/M///ZgD/ZjP/Zmb/Zpn/Zsz/"
    "Zv//mQD/mTP/mWb/mZn/mcz/mf//zAD/zDP/zGb/zJn/zMz/zP///wD//zP//2b//5n//8z/"
    "//8AAAA5OTmPj4+FhYU5OTkwMDBYWFh/f39ycnI6OjpLS0sxMTF9fX0qKiqqqqphYWEtLS1d"
    "XV2MjIw3NzdcXFyRkZFiYmI3NzcMDAwwMDBRUVFQUFAkJCQuLi5NTU1OTk6oqKhEREQBAQEu"
    "Li6rq6tTU1MREREpKSm84CzqAAABAHRSTlP/////////////////////////////////////"
    "////////////////////////////////////////////////////////////////////////"
    "////////////////////////////////////////////////////////////////////////"
    "////////////////////////////////////////////////////////////////////////"
    "//////////////////////////////////8A1ZxBzdQrBEfX/4xJBgZu/mg84ZUVJ7P/yxmP"
    "0f+yNETR/uJSa+j2ZUgoxgAAAAlwSFlzAAAOwwAADsMBx2+oZAAABBZJREFUaIHtWX2e4yAI"
    "9T7eh/vkPnOgHGc7SVU+3iPjNLv7axr+ahGBp4BoyvohVP63A/+KbqBXoxvo1egGejW6INBa"
    "EfeCQEtBUC8J9EEB6lWBBqgWaC0J1Teh4TAFmuJ8Q6qfAvQBVT4DaP0QoDR0Vxm0SyrG8iYk"
    "DaUtu/R42WQXNvq36euFuU+c4rhEel8XNDC2mNv6rvIC2GhW4EmNni7SFC5CaECCW8SAVh/j"
    "mj+SALaVTyHClshUWkQZUFCHFM1HGbJokVOgaFOSfHcy0RaaYe1Uor0D5fVy6ABuc6Bo8Y2d"
    "Ggw4QGEN2gwJXD+ztPam6oEdqGuAxn8C5ADoHkGA3ww+ksI7kwMa/Bq4RqK5rGN6qxh72vWc"
    "3IVjis4BzVK05lLSdoTtqCv7bt+0ejFTU1cOaRKoC1YUu7WHXpxbxevV7jKjKnLJzB/QPFCd"
    "DZsxGzV7cAsGWsS7p1eEpPyKQXFpSBnQGPeSuKlYsi41zN+x+xkqRVld6Eqd56fs6LZcsT1B"
    "bsYbbV39qTFGxPmsKw4PRrACqj79iDBQ1hdlGWYlYNX5RmgHdIjnQGFpg8KYeKgcF10gZg92"
    "72wJKkwuU6A+Y5q6icjNgKI+6iByR1EN1UgU0GLODXa6WDtoRw8PT+065mKgDliyoXETzF7H"
    "jqfrY4eaY/tcPyQIlKWo8VEwzmbda4BBLWDlAFKw7LMpioGmKdpbziikV5kC1T2Dz3ncVaJD"
    "ebJd+AVQQ+ikJJ4McTXi7fT+2Sg+oQGcBGpRhuuQMY6ABr8DhKUrZ3pXMvOIZoCKBQpvJ0Ox"
    "VaF3ewzV6C24FLG+KIEVCUpvhmLXsdeacUFL3wpAha7hN1zPgBQtxylAwxWjyQ7tpQRL/k3E"
    "CuiF6WuAGoG11yRRc1+O3Gmg9Eq1OMZiszg8JNSV74s9uVhf9DrQ5OrCi83zdcA+dZDwa3Np"
    "6awayBl9EQYKS40PFxc8rlA10jpjh4vtdO0CLW0KTgG6kLhwK2u9DEesLShgbs1Kp77RlxKe"
    "VedTFAFlKQquLvZRJ36ntG2sV0Vq0ebWkEdS0+0CBMquLgAobs6Bg+h+l9w/06Zi/U2KUqDH"
    "d4jD1x7NK/Zg3l9akgBUtpA3J+4o6YuUs0X9hzMUE1/ayIKudhFP6Ysg0KIKATHe/wscCh7i"
    "JxddWU25MUsAdCfJTYl8CvrB7XekGEk2xY270qr0UN7Xtr3BK0Gn+Ryg2a3bONuRJ1VaFZQl"
    "Drok/67U7aNK3+FTri7rxI7GM/oIaLFAgRUbn5rs14hXH8a2Odi/4xQ9buRUErNdcY1Wh8lO"
    "sZ1+0RfBHSXf4CL7yRH8eXsf6JJBwtmR1mM4M8gbwR6mNBvqb0s30KvRDfRqdAO9Gt1Ar0Y3"
    "0KvRxwD9A0ze2goiArxqAAAAAElFTkSuQmCC")

